### ISSUE TITLE
Import of upper-case Sirupsen/logrus on gopkg

### ISSUE THREAD

**Issue by shedimon** [gemnasium/logrus-airbrake-legacy-hook#1]
go get gopkg.in/gemnasium/logrus-airbrake-legacy-hook.v1 ends with the version, that refers to tag 1.0.0, that uses old import

**Comment by gravis** [comment]
Thanks for reporting this.
I have released [1.0.1](https://github.com/gemnasium/logrus-airbrake-legacy-hook/releases/tag/v1.0.1) to fix the issue

(refs 8895bb2576ec92d9a1f44900496659f69a3a7ad1)
