### ISSUE TITLE
New Trace level in logrus

### ISSUE THREAD

**Issue by dgsb** [gemnasium/logrus-airbrake-legacy-hook#2]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named `Trace` below `Debug`.
Here is the PR for reference sirupsen/logrus#844
You may/want to take into account this new level.

**Comment by loren-osborn** [comment]
Just a heads up, looking at the code in this project now, it only seems to be aware of 
- `ErrorLevel`
-  `FatalLevel`
-  `PanicLevel`
As it has no knowledge of `WarnLevel`, `InfoLevel` or `DebugLevel`, I doubt it would care to know about `TraceLevel` for any reason.

**Comment by gravis** [comment]
> As it has no knowledge of WarnLevel, InfoLevel or DebugLevel, I doubt it would care to know about TraceLevel for any reason.

You're absolutely right, thanks!
/close
